version: '3.4'

services:
  moviesapi:
    container_name: moviesapi
    image: ${DOCKER_REGISTRY-}moviesapi
    environment:
     - ASPNETCORE_URLS=https://+:5001;http://+:5000
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/moviesapi.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=TuPasswordSeguro
    build:
      context: ../
      dockerfile: MoviesAPI/MoviesAPI/Dockerfile
    ports:
    - "5000:5000"
    - "5001:5001"
    volumes:
     - ./MoviesAPI:/src/MoviesAPI
     - ./Data:/src/MoviesAPI/Data
     - ./Core:/src/MoviesAPI/Core
     - ./Services:/src/MoviesAPI/Services 
     - ~/certs:/https:ro
    depends_on:
        database:
         condition: service_healthy
   
    
  database:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: database
    ports:
    - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd123 
    volumes:
    - ./sqlserver/data:/var/opt/mssql/data
    - ./sqlserver/log:/var/opt/mssql/log 
    healthcheck:
     test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U SA -P "YourStrong@Passw0rd123" -Q "SELECT 1" -No
     interval: 10s
     timeout: 3s
     retries: 10
     start_period: 10s



  frontend:
    container_name: front
    image: ${DOCKER_REGISTRY-}front
    build:
        context: ./Client/frontend
        dockerfile: Dockerfile
    ports:
     - "4000:4000"
    volumes:
      - ./Client/frontend:/app  
      - /app/node_modules
 

